### ISSUE TITLE
Question ... on botania/intangible

### ISSUE THREAD

**Issue by monkeyfuzzz** [williewillus/Botania#116]
still having trouble with  crafting  managlass... this guy said this 
MrGraphic commented a day ago

No problem and if you ever want to use Blow Mold from Intangible that requires this "converted dropped glass" after turning it off just use dropper and it will spit out this one despite configs.

what is a dropper  and what does he mean " it will spit out this one"?

**Comment by MrGraphic** [comment]
http://minecraft.gamepedia.com/Dropper

If you turn off in Intangible's config converting dropped glass to Intangible equivalent then you will be able to get managlass but unable to get items from Intangible. This config however will only turn off converting for players not for droppers - not sure about other "droppers" like blocks from other mods.

**Comment by williewillus** [comment]
Basically, 
1. Whenever you drop glass, Intangible replaces it with its own glass entity
2. This entity is not an EntityItem and thus isn't detected by the mana pool -> no transmutation
3. Intangible has an option where player-dropped item isn't converted but dropper dropped ones are, so that can be used for now.
