### ISSUE TITLE
Thaumcraft messes with complex brews

### ISSUE THREAD

**Issue by Hyxaru** [williewillus/Botania#148]
Most likely a potion id conflict, resulting in complex potions gaining effects like flux phage, unnatural hunger etc.

**Comment by williewillus** [comment]
Can you reproduce this reliably/give me steps to do so?

**Comment by williewillus** [comment]
Both botania and thaumcraft use the forge provided 1.8 potion registry to acquire their ID's, there shouldn't be any problems

Unless the brews use number ID's, which may very well be possible. Will investigate. Does it happen when switching between different worlds where thaumcraft/botania were added different times?

Edit: Brews do use number ID's, only because vanilla does in PotionEffect. Reading based on ID's should be safe according to boni, though.
