### ISSUE TITLE
A gamebreaking bug

### ISSUE THREAD

**Issue by BerciTheBeast** [williewillus/Botania#151]
It appears a game-breaking bug has re-appeared with the latest update.

Passive flower decay configuration seems to have been re-enabled. I thought this bug was fixed quite a while back? Anyway, I trust that this issue will be resolved in the near future (for the good of the people, nothing less!).

**Comment by williewillus** [comment]
check the upstream changelog [botaniamod.net/changelog.php](http://botaniamod.net/changelog.php)

**Comment by BerciTheBeast** [comment]
Yep, as i said. A game-breaking bug has been reintroduced.

**Comment by williewillus** [comment]
If it's his will, so be it.
I was contemplating re removing the config in 1.8, but I'm scared of the possible shitstorm.
We'll see after things have cooled off a bit

**Comment by TheWhiteWolves** [comment]
Just to throw my thought in on this, I still agree with why we removed it in the first place and would be ok with it being removed again (i.e. I think it should be removed), I did say to vaz that we should leave it but she was tired of the constant stream of hate about it from those who were playing before it was introduced.

If you want to remove it I would suggest sooner rather than later so that 1.8 players don't get used to it being there.
