### ISSUE TITLE
[REQUEST - 1.9] Allow making monster drops with Mana Pool

### ISSUE THREAD

**Issue by novasolarius** [williewillus/Botania#236]
_sigh_ A new version, a new search for mods, new problems. And then I find that Botania has a 1.9 prerelease! Amazing!

Here's the short version: I play on peaceful, leaving me without a source of mob stuff. And since Botania requires so many Ender Pearls and so much string, I was hoping you would be willing to add Mana Pool recipes for making 'em. They don't need to be cheap, just there.

Many thanks for updating Botania (W00T!) and I hope you consider my request. Thank you very much for reading.

**Comment by Lashriel** [comment]
I don't think this is going to happen, mostly for balance reasons.

That said, I think there is an amusingly post-Nether way to get String from Wool. Not helpful in the slightest since it requires an Alchemy Catalyst, but worthy of note.

**Comment by novasolarius** [comment]
You're right, that doesn't help. But what's wrong with making mob stuff balance-wise?

**Comment by Lashriel** [comment]
For starters, Botania adds methods of spawning and killing mobs. You'd basically be invalidating Botania mob spawners unless you made the items prohibitively expensive or locked the recipes to Peaceful-only, which is pretty complicated in 1.(8.)9 IIRC.

PS. A bunch of mob drops are still available in dungeon chests or as villager trades. I think that includes Ender Pearls and Bones, but not Blaze Rods. I think adding Blaze Rods to Nether Fortress chests would make everything up to the Wither/Gaia accessible, so that might be a fair compromise.

**Comment by novasolarius** [comment]
...how did I forget the Loonium again? Never mind then, I'll just make a few of those.

But seriously, how hard is it to check what the difficulty level is? If it's not too hard, shouldn't it be possible to check when somebody attempts to transmute... let's say an emerald into an Ender Pearl, then allowing that transmutation only if the difficulty is zero?

**Comment by yrsegal** [comment]
it isn't hard to check difficulty. it _is_ decently hard to have dynamic recipes.

**Comment by novasolarius** [comment]
Ah. Okay, fair enough. I'll just close this issue then.
