### ISSUE TITLE
 crash when assigning some recipes to assembly halo

### ISSUE THREAD

**Issue by aubreybailey** [williewillus/Botania#314]
specifically:
forge 1.9v1934
botania 305
baubles 1.2.0.2 (required dependency)
Pams harvestcraft 1.9b 
flour recipe (shapeless mortar and pestle with wheat)
is crafted in the assembly halo and then assigned to the first slot to the right.

Tested in new game with creative and only these mods. (I realize that you're building for 1.9.4 now, but some mods are still back on 1.9.0)
Please and thank you,
Aubrey

**Comment by williewillus** [comment]
fix won't be for 1.9.0 but will be in 1.9.4, do you have a crashlog I can look at ?

**Comment by ImmortalGriffin** [comment]
Same problem here is my  Report 
[crash-2016-06-01_16.51.17-client.txt](https://github.com/williewillus/Botania/files/294355/crash-2016-06-01_16.51.17-client.txt)

**Comment by williewillus** [comment]
@ImmortalGriffin can you report it ExU? The halo is crashing trying to render one of its models.

I don't think it's on my end because I very simply render it like so: https://github.com/williewillus/Botania/blob/ff2afbf03748ffaeaf4ea5956ba65d749249c252/src/main/java/vazkii/botania/common/item/ItemCraftingHalo.java#L471-L471.

That is the same mechanic that enderman use to render carrying or carts to render  in the cart.

@aubreybailey I need your log but I suspect the same

**Comment by yrsegal** [comment]
You should be using the itemstack renderer for everything I think, willie
It renders blocks as well as items

**Comment by williewillus** [comment]
oh yeah, derp.

That was ported directly from 1.7

jk don't report it to exU yet

**Comment by yrsegal** [comment]
I have code which works for the Traveller's Toolbelt, [here](https://github.com/yrsegal/NaturalPledge/blob/master/src/main/java/shadowfox/botanicaladdons/common/items/travel/bauble/ItemToolbelt.kt#L197-L206)

**Comment by yrsegal** [comment]
It also looks much more correct, since the item looks how it does in a GUI instead of just being inworld
