### ISSUE TITLE
Noise cancellers

### ISSUE THREAD

**Issue by williewillus** [williewillus/Botania#397]
From a vanilla+Botania perspective, we need some. Notes so I don't forget. 
- generating flower? (tiny tiny amount, probably even less than daybloom)
- functional flower? (no or tiny cost)
- Bauble? `(set! *botania-noise-cancelers* true)` <- lispers know what I mean :D

**Comment by yrsegal** [comment]
But that's NP's thing ;-;

**Comment by Sunconure11** [comment]
Bauble or functional flower would be the way to go to IMHO. Generating flower, if done, should have the same drawbacks as dayblooms, as it would be too easy to set up a chicken farm near one, inside of a small pen.

**Comment by williewillus** [comment]
@yrsegal botania+vanilla needs it :P

**Comment by Lashriel** [comment]
I think it should be a functional flower, much like the Solegnolia. It's a tiny QOL utility that really shouldn't have too big of a cost - heck, if I get the intent right it's much like ExtraUtilities' sound muffler, which was cheap to make (1 redstone, some wood and some wool) and had zero running cost.

I don't think it should be a bauble, for one because it sounds more useful to have it bound to an area instead of to the player (also volume controls are a thing), and also because I'd probably forget to take it off and then not hear something I really need to.
Plus, there's already so many other Baubles that I'd want to put in any given slot.

**Comment by yrsegal** [comment]
Bauble doesn't intrude on NP's design space :3

**Comment by williewillus** [comment]
I was thinking bauble but I'm leaning on func flower

**Comment by williewillus** [comment]
He raises a good point baub is pointless because it follows the player and volume sliders do the exact same

**Comment by yrsegal** [comment]
True, true... This makes the Sealing Tree useless though :( 
(unless you make it require mana, which makes little sense)

**Comment by williewillus** [comment]
I don't know what that is :D
It'll be like the solegnolia

**Comment by yrsegal** [comment]
Sealing Tree is a sound muffler tree from Natural Pledge.
