### ISSUE TITLE
Mana Enchanter can violate normal enchanting limits

### ISSUE THREAD

**Issue by belathus** [williewillus/Botania#405]
Some mods add recipes for items that violate the normal enchanting limits. For example, Evilcraft has the vengeance pickaxe that comes with fortune X, or Progressive Automation's withered tools have unbreaking X. You can strip these enchantments from the tools onto books with Evilcraft's purifier, MFR's autodisenchanter (if it updates), and PneumaticCraft. Trying to reapply the book using a vanilla anvil resets the enchantment back to the normal limit (fortune 3, unbreaking 3), but the mana enchanter does not.

**Comment by yrsegal** [comment]
I feel like the disenchanters should be dealing with this, not the enchanter.

**Comment by Lashriel** [comment]
I, too, think this doesn't need to happen on Botania's side, but for a different reason.

For starters, Evilcraft adds both the tool and the disenchantment mechanic, which leads me to believe that this is fully intentional on their part - if not, that's their problem to deal with.

Also, I think the Mana Enchanter was deliberately designed to allow any enchantment level you somehow get your hands on, specifically _because_ there's ways to break enchantment limits which the Anvil doesn't respect. I've seen maps where Level X Enchanted books were used as a reward, and then the Anvil would turn it back into a normal-max-level enchant.

**Comment by belathus** [comment]
Evilcraft allows you to both get fortune X and strip it, but the only method of getting fortune X on another tool that I am aware of is Botania. That is why I reported it here. Anvils won't do it. Even modded anvils won't (Thaumic Bases, anyway). I guess if we had Draconic Evolution, we can stuff the books in those tools, so there is that.

**Comment by MaPePeR** [comment]
If there is a book of an enchantment I see no reason to not apply it. If it is unbalanced or not intended then the book is useless and should not be available in the first place. 

I think the bug is, that the vanilla anvil does not apply the book correctly.

**Comment by vladfrangu** [comment]
@MaPePeR Actually.. Its intended. Mineraft maxes out at Fortune level 3. Thus, the anvil only allowing level 3 fortune (Just an example)
`public int getMaxLevel()
    {
        return 3;
    }`

This line of code sets the maxium you can obtain in vanilla ways.. The fact that you can get "Illegal" enchants level isn't intended, but it exists

**Comment by williewillus** [comment]
how about this compromise:
If the enchantment is "illegal" it applies, but the book is destroyed

**Comment by yrsegal** [comment]
ooo, that sounds good (especially with the quark treasure books)

**Comment by Lashriel** [comment]
I'm still of the opinion that this isn't necessarily a problem that needs 'fixing' on Botania's end in the first place, TBH. If an enchanted item isn't supposed to be strippable, it's on the creator of either the enchanted item or the disenchanter to make it so, IMHO.

Also I don't know what to do about the Quark treasure books. Part of me wants to be able to re-use at least those, since they work in a regular anvil.

How about if an enchant is 2 levels or more over its normal anvil maximum, the book gets destroyed?

**Comment by MaPePeR** [comment]
@KingDGrizzle there is no way to get an enchantment like that in vanilla minecraft. If a mod gives you a book with any enchantment it does that with the purpose that you can apply that enchantment to a tool. So if the anvil does not apply the enchantment from the book, it destroys the purpose and intention of the book.

**Comment by vladfrangu** [comment]
@MaPePeR You "can" via the /give command and using the {ench:[]} tag

Examples could include: `/give @p minecraft:diamond_sword 1 0 {ench:[{id:16,lvl:1000}]}`

**Comment by Lashriel** [comment]
@MaPePeR Actually there is, you can use commands to /give yourself pretty much any enchanted item. You can get a Knockback X enchanted Sign in vanilla Super Hostile maps - they were spawned in that way.

**Comment by MaPePeR** [comment]
okay.... i didn't thought i had to rephrase that for you: there is no legitimate way, that does not involve using cheat commands, to obtain such enchantments in vanilla.

For the custom maps you mention: the anvil bug actually limits map creators, because they cannot give you such an enchantment book to apply to your tools yourself.

**Comment by vladfrangu** [comment]
@MaPePeR They can test for a item that has a legal enchant, and a custom tag, and then replace it.. Ain't that hard

**Comment by williewillus** [comment]
Keep it on topic please.

**Comment by williewillus** [comment]
I am leaning towards either leaving it as is or doing the compromise I mentioned above

**Comment by yrsegal** [comment]
compromise is my opinion for a better one, especially because it doesn't trivialize quark treasure enchants.

**Comment by Lashriel** [comment]
I'm okay with the compromise, but I don't necessarily think it trivializes the Quark treasure enchants to have them be re-usable in a Mana Enchanter.

Not any more so than using a Loonium to get them, in any case.

Although maybe an alternative compromise is to have it become substantially more expensive mana-wise if you break Anvil limits. Thoughts on that?

**Comment by williewillus** [comment]
This will be left as is unless @Vazkii has any extant opinion on it
