### ISSUE TITLE
Issues regarding mod sorting

### ISSUE THREAD

**Issue by T4ge** [williewillus/Botania#53]
Got this error while updating to Thaumcraft 5.1.4 and forge 11.15.0.1710/11.15.0.1701
http://pastebin.com/DZ9q9VMV
Does not happen without botania installed

**Comment by rougebare** [comment]
This also does not happen with Thaumcraft 5.1.3 installed in place of 5.1.4. This is most likely due to Thaumcraft adding support for the petal apothecary with the everful urn, likely creating some sort of loop where the everful urn needs botania loaded and botania's tc integration (like the mana helms of revealing) need thaumcraft.

**Comment by T4ge** [comment]
I'll report it to Azanor as well, so either one can figure it out

**Comment by ThomasRules2000** [comment]
I think this issue is to do with botania's api loading, which needs to be after botania and before thaumcraft, but botania itself wants to load after thaumcraft. This may be as thaumcraft is requesting that botatia's api load for integration, which needs botania, but botania itself is waiting for thaumcraft to load for its integration.

Would it be possible to init thaumcraft related botania items in the init() stage to remedy this?

**Comment by williewillus** [comment]
Probably, yes
