### ISSUE TITLE
botania.common.block.tile.mana.TilePool.recieveMana Crash

### ISSUE THREAD

**Issue by whatthedrunk** [williewillus/Botania#67]
http://pastebin.com/aK9xwLXR

**Comment by williewillus** [comment]
Duplicate, bandaid in next build

**Comment by whatthedrunk** [comment]
Any idea when a new build will be made? I tried myself but had issues with the gradlew build.

**Comment by williewillus** [comment]
early next week

**Comment by whatthedrunk** [comment]
Thanks a ton. Any way to donate to you besides Patreon? Been wanting to send a really small thanks but not a fan of Patreon for personal reasons.

**Comment by williewillus** [comment]
I totally understand, Patreon is a little much for me to do, I just have it up just because it existed before :p
I have plugs for all donation links (original devs + my patreon + a paypalme) on major build notes: https://github.com/williewillus/Botania/releases

Again, thank you so much, I hope you're enjoying it!

**Comment by williewillus** [comment]
@whatthedrunk New build https://github.com/williewillus/Botania/releases

**Comment by whatthedrunk** [comment]
Thank's a ton for pushing out an update early! Unfortunately I am still getting the same crash.
